# Prometheus config when all services run in Docker Compose
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "event-sourced-cqrs"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "command-service:8081"
          - "query-service:8083"
