# Prometheus config when running everything on host (Kafka + apps locally)
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "event-sourced-cqrs"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "localhost:8081"   # command-service
          - "localhost:8083"    # query-service
